process_count: 4
updating_step: 10
finding_step: 10
expiration_time: 36000 # 60 * 60 * 10
backup: False
debug: False
safe_mode: False

sftp: None

local_save: False
save_page_local: True

mongo:
  ip: 198.143.179.211
  port: 27017
  username: admin
  password: parishadbg18
  authentication_db: admin

dir:
  main: ./..
  project: ./../guessit-data-manager
  dataset: ./../datasets
  download_page: ./../download/page